### ISSUE TITLE
Crash on load(1.11.2)

### ISSUE THREAD

**Issue by IronworksProductions** [ExpensiveKoala/Avaritia-and-RefinedStorage#1]
I started a modpack. I setup with this mod through curse app/twitch app. I have the error log here: https://hastebin.com/fazodaviwi.sql
is there some mod curse missed?

-----
Thanks

NN

**Comment by ExpensiveKoala** [comment]
You're using version Avaritia 3.0.2 which doesn't have any of the items which I'm counting on for the recipes. So you'll need to use Avaritia 3.1.0. It's still an alpha release so there probably will be issues. I probably should have made my mod require that version forward, but oh well.
