### ISSUE TITLE
Potential World Corruption with Reborn storage multiblock

### ISSUE THREAD

**Issue by LiquidLighter** [ExpensiveKoala/Avaritia-and-RefinedStorage#11]
I have around 800+ hours on a world in foolcraft3 version 1.5.4
I found that i can use a auto crafting multi structure instead of like 100 craters from refined storage.
So i immediately built the max size for the multi structure of 16x16 and i was able to put all my patterns in.
After a few minutes my game crashed and i can no longer load into the world no matter what i try
I made a new world and attempted to recreate the problem, as soon as i placed down any of the multi structure blocks (i.e frame) i get an error from Refined Avaritia (by pressing crtl-I after being prompted)

**Comment by ExpensiveKoala** [comment]
Do you have any error logs?

**Comment by LiquidLighter** [comment]
sorry, i initially submitted this for reborn storage and forgot to copy paste the link here also
Just some extra info. I had like 800+ CPU's within the multi block yet it was going at the same speed of a single crafter, that's when i noticed there was something wrong

report link i was given https://paste.dimdev.org/cequlolegu.mccrash

**Comment by ExpensiveKoala** [comment]
Oh this is the same crash as #9.
I'm planning on fixing it either this weekend or the next. Been pretty busy with other stuff lately

**Comment by LiquidLighter** [comment]
oh okay, will be looking forward to the fix, thanks!
