### ISSUE TITLE
Compatibility with Extended Crafting Tables

### ISSUE THREAD

**Issue by Freebi85** [ExpensiveKoala/Avaritia-and-RefinedStorage#13]
Hello =)

Wanted to ask if there is a possibility to integrate extended crafting tables as well. The Mod has 5x5, 7x7 and 9x9 Crafting Tables. If you got the time and desire^^

**Comment by ExpensiveKoala** [comment]
There already is integration with extended crafting. Unfortunately, I haven't worked on any gui for it though.

If you set the recipe in the table and right click on it with a pattern, you will save the recipe into the pattern.

**Comment by Freebi85** [comment]
Oh WoW this is amazing =)
Thank You!
