### ISSUE TITLE
Whenever setting an extreme pattern with the extreme pattern encoder, the game crashes whilst rendering screen.

### ISSUE THREAD

**Issue by Xenomorphobe** [ExpensiveKoala/Avaritia-and-RefinedStorage#4]
(https://github.com/ExpensiveKoala/Refined-Avaritia/files/2233774/crash-2018-07-26_18.24.22-client.txt)

**Comment by Xenomorphobe** [comment]
It happens when you hover over an extreme pattern that has been set, not when you encode it.

**Comment by ExpensiveKoala** [comment]
It seems like Refined Storage changed something in their code. I will update the mod so it will work with the updated Refined Storage.

**Comment by Ax1007** [comment]
On top of that.

If you take the Pattern out by destroying the Encoder, then dropping the pattern into a hopper to a Crafter (to avoid seeing the tooltip), the pattern dissapears completely (strangely happens with empty Extreme Patterns too)

I cant work out how to get the pattern into a Crafter without crashes to see if it actually works correctly or not.

**Comment by gaminggirl** [comment]
Same problem here, here is my crash log: https://gist.github.com/gaminggirl/baf64653479445b1484504e52b3ad9d7
